name: CI Symfony

on:
  push:
    branches: [ main, ci/github-actions, test/Ajout-tests ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: ina_zaoui_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    env:
      DATABASE_URL: "mysql://root:root@127.0.0.1:3306/ina_zaoui_test"


    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: pdo_mysql
          coverage: none


      - name: Install Composer dependencies
      
        run: composer install --prefer-dist --no-progress 

      - name: Drop database
        run: php bin/console doctrine:database:drop --force --if-exists --env=test


      - name: Create database
        run: php bin/console doctrine:database:create --env=test

      - name: Run migrations
        run: php bin/console doctrine:migrations:migrate --no-interaction --env=test

      - name: Load fixtures
        run: php bin/console doctrine:fixtures:load --no-interaction --env=test

      - name: Debug DATABASE_URL
        run: echo "DATABASE_URL=$DATABASE_URL"

      - name: Debug DATABASE_URL
        run: echo "DATABASE_URL=${{ env.DATABASE_URL }}"


      - name: Run tests
        run: php bin/phpunit

      - name: Check Symfony logs (dev.log)
        run: cat var/log/dev.log || echo "No dev.log found"

      - name: Vérifie que PHPStan est installé
        run: |
          ls -la vendor/bin
          test -f vendor/bin/phpstan && echo "✅ PHPStan installé." || exit 1

      - name: Run PHPStan (analyse statique)
        run: composer phpstan analyse --memory-limit=1G

